# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7ecb57c3cbe103bb659936a2841c60b4"
name = "Blocksmith"
application_url = "https://blocksmith.m8lab.co"
embedded = true
handle = "blocksmith-ai"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app/subscriptions_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
# write_app_proxy is REQUIRED for App Proxy to work
scopes = "write_files,write_products,write_themes,write_app_proxy,read_content"

[auth]
redirect_urls = [ "https://blocksmith.m8lab.co/api/auth" ]

[app_proxy]
url = "/api/proxy/render"
subpath = "blocksmith-preview"
prefix = "apps"
